GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "botx-465316",
  "private_key_id": "41127c829555a0659b9be493422a758c3e7603e2",
  "private_key": "-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCvpyPIi/ycH9PD
BG5Kvcj7bNUs8Jrbr2sDNKyo+zmKxM30YtLidrREWHllzZ2+RROJYiwSRvuFSXIp
... (más líneas aquí)
-----END PRIVATE KEY-----",
  "client_email": "bot-x-service@botx-465316.iam.gserviceaccount.com",
  "client_id": "112877517540322589379",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/bot-x-service%40botx-465316.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
