GOOGLE_CREDENTIALS = """
{
  "type": "service_account",
  "project_id": "botx-465316",
  "private_key_id": "41127c829555e0e2b7e0e2b7e0e2b7e0e2b7e0e2b7e0e2b7e0e2b7e0e2b7e0e2",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASC...\\n...\\n-----END PRIVATE KEY-----\\n",
  "client_email": "botx-465316@botx-465316.iam.gserviceaccount.com",
  "client_id": "116835123456789012345",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/botx-465316%40botx-465316.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
